<a href="https://colab.research.google.com/github/r-matsuzaka/atcoder/blob/main/colab/248_c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [C - Dice Sum](https://atcoder.jp/contests/abc248/tasks/abc248_c)
## [解説](https://atcoder.jp/contests/abc248/editorial/3745)
## [解説(包助原理)](https://atcoder.jp/contests/abc248/editorial/3818)

In [1]:
# マス目上の最短経路の本数
# N×N のマス目において、左上のマスから右下のマスまで最短で至る経路の本数
# 配るDPの場合

import numpy as np

N = 3

dp = [[0]*N]*N
dp = np.array(dp)

dp[0,0]= 1

for i in range(N):
  for j in range(N):
    if i - 1 >= 0:
      dp[i][j] += dp[i-1][j]
    if j - 1 >= 0:
      dp[i][j] += dp[i][j-1]

print(dp)
ans = dp[N-1][N-1]
print(ans)

[[1 1 1]
 [1 2 3]
 [1 3 6]]
6


In [2]:
# 解法1:包助原理の解法
# 答えが合わない

import functools as ft


def permutation(n, k):
    if k > n:
        return 0
    elif 0 < k <= n:
        return ft.reduce(lambda x, y:x * y, [n - v for v in range(k)])
    else:
        return 1


def factorial(n):
    return permutation(n, n - 1)


def combination(n, k):
    return int(permutation(n, k) / factorial(k))


def combination_with_limit(N, M, K):
    return sum([(-1)**L * combination(K-M*L, N) * combination(N, L) for L in range(N+1)])

# N, M, K = (2, 3, 4)
N, M, K = (321, 41, 592)
pattern = combination_with_limit(N, M, K)
ans = pattern%998244353
print(ans==798416518)

False


# Reference
- [【応用】指定した合計値になる整数の組合せ](https://math.nakaken88.com/textbook/expert-combination-of-integers-whose-sum-is-the-given-value/#i-3)
- [個数制限がある場合の重複組合せの総数を動的計画法で求める](https://www.sambaiz.net/article/306/)
- [Python/Ruby/PHP/Golang(Go)で上限のある重複組み合わせ](https://qiita.com/hiroykam/items/3886d6a213cd593fdfab)
- [貰う DP と配る DP](https://algo-method.com/descriptions/78)